server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service 
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: car-service 
          uri: lb://car-service
          predicates:
            - Path=/car/**
        - id: motorbike-service 
          uri: lb://motorbike-service
          predicates:
            - Path=/motorbike/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5