spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: Circuit-Breaker
          uri: https://github.com/YuukoI/MicroservicesWithSpringCloud
          search-paths: config-data
server:
  port: 8084